version: "2"
services:
  svn:
    build:
      context: ../
      dockerfile: build-contracts/ui/Dockerfile
    environment:
      ADMIN_REST_ACCESS: "true"
      RWEB: fpm
      AUTHN: anon
    # Uncomment ports and volumes for client side development, but comment out for build
    # Rweb will only work when this service is accessed through a http://svn/ hosts file record
    #ports:
    #  - "80:80"
    #volumes:
    #  - ./ui:/usr/local/apache2/htdocs
  rweb:
    image: solsson/rweb:latest
    expose:
      - "9000"
  unittests:
    build:
      context: ../
      dockerfile: build-contracts/unittests/Dockerfile
    labels:
      - "com.yolean.build-contract"
  client:
    labels:
      - "com.yolean.build-contract"
    build: ./client
    environment:
      DEBUG: $DEBUG
    volumes:
      - ../:/usr/src/app/node_modules/repos-upload
    links:
      - svn