version: "2"
services:
  svn:
    image: solsson/rweb-httpd:latest
    environment:
      ADMIN_REST_ACCESS: "true"
      RWEB: fpm
      AUTHN: anon
  rweb:
    image: solsson/rweb:latest
    expose:
      - "9000"
  client:
    labels:
      - "com.yolean.build-contract"
    build: ./client
    environment:
      DEBUG: $DEBUG
    volumes:
      - ../:/usr/src/app/node_modules/repos-upload
    links:
      - svn